### ISSUE TITLE
Is the repo up to date?

### ISSUE THREAD

**Issue by joliss** [lwneal/gptwc#1]
Hi Lawrence, thanks for this tool, it's very useful!

I wanted to send a quick PR, but I'm noticing that setup.py shows version 1.2.2, whereas PyPI has version 1.2.4. So before I make edits, I just to wanted to double-check if you had pushed the latest changes to GitHub?

**Comment by lwneal** [comment]
Thanks for checking, there was an outstanding commit that I've pushed to the repo.
